services:
  - type: web
    name: travelbot-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: "<YOUR_OPENAI_API_KEY>"
