# Shared Backend Deployment Configuration
services:
  - type: web
    name: travelbot-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        sync: false
