name: Build TravelBot iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'travelbot-ipa-builder/package-lock.json'

    - name: Install Capacitor CLI
      run: |
        npm install -g @capacitor/cli @ionic/cli
        cap --version

    - name: Navigate to Capacitor project and install dependencies
      run: |
        cd travelbot-ipa-builder
        npm install

    - name: Sync Capacitor iOS
      run: |
        cd travelbot-ipa-builder
        cap sync ios

    - name: Build iOS project with Xcode
      run: |
        cd travelbot-ipa-builder/ios/App

        # Verify workspace exists
        if [ ! -d "App.xcworkspace" ]; then
          echo "❌ Error: App.xcworkspace not found. Capacitor sync may have failed."
          exit 1
        fi

        # Build and archive the app without signing
        echo "🏗️ Building and archiving iOS app..."
        xcodebuild clean archive \
          -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -allowProvisioningUpdates

    - name: Create unsigned IPA
      run: |
        cd travelbot-ipa-builder/ios/App

        # Verify required files exist
        if [ ! -d "App.xcarchive" ]; then
          echo "❌ Error: App.xcarchive not found. Previous build step may have failed."
          exit 1
        fi

        if [ ! -d "App.xcworkspace" ]; then
          echo "❌ Error: App.xcworkspace not found."
          exit 1
        fi

        # Create build directory
        mkdir -p ./build

        # Create single export options plist for unsigned distribution
        cat > export-options.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key>
          <string>app-store</string>
          <key>signingStyle</key>
          <string>manual</string>
          <key>compileBitcode</key>
          <false/>
          <key>stripSwiftSymbols</key>
          <true/>
          <key>thinning</key>
          <string>&lt;none&gt;</string>
          <key>uploadBitcode</key>
          <false/>
          <key>uploadSymbols</key>
          <false/>
        </dict>
        </plist>
        EOF

        # Export IPA from archive
        echo "📱 Exporting IPA from archive..."
        if xcodebuild -exportArchive \
          -archivePath App.xcarchive \
          -exportPath ./build \
          -exportOptionsPlist export-options.plist \
          -allowProvisioningUpdates; then
          echo "✅ Archive export successful"
        else
          echo "⚠️ Archive export failed, attempting manual IPA creation..."
          
          # Fallback: manually create IPA from .app bundle
          APP_PATH="App.xcarchive/Products/Applications/App.app"
          if [ -d "$APP_PATH" ]; then
            echo "📦 Creating IPA manually from .app bundle..."
            mkdir -p ./build/Payload
            cp -R "$APP_PATH" ./build/Payload/
            cd ./build
            zip -r App.ipa Payload/
            cd ..
            echo "✅ Manual IPA creation successful"
          else
            echo "❌ Error: App.app not found in archive"
            echo "Archive contents:"
            find App.xcarchive -name "*.app" -type d || echo "No .app bundles found"
            exit 1
          fi
        fi

        # Verify IPA was created and rename it
        if [ -f "./build/App.ipa" ]; then
          mv "./build/App.ipa" "./build/TravelBot-4.0.0.ipa"
          echo "✅ IPA successfully created: TravelBot-4.0.0.ipa"
        else
          echo "❌ Error: IPA file not found after export"
          echo "Build directory contents:"
          ls -la ./build/ || echo "Build directory not found"
          exit 1
        fi

        # List final build results
        echo "=== Final Build Results ==="
        ls -la ./build/

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: travelbot-ios-app
        path: |
          travelbot-ipa-builder/ios/App/build/*.ipa
        retention-days: 30

    - name: List build results
      run: |
        echo "=== Build Results ==="
        ls -la travelbot-ipa-builder/ios/App/build/ || echo "Build directory not found"
        find travelbot-ipa-builder/ios/App -name "*.ipa" -type f || echo "No IPA files found"
