name: Build TravelBot iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'travelbot-ipa-builder/package-lock.json'

    - name: Install Capacitor CLI
      run: |
        npm install -g @capacitor/cli @ionic/cli
        cap --version

    - name: Navigate to Capacitor project and install dependencies
      run: |
        cd travelbot-ipa-builder
        npm install

    - name: Sync Capacitor iOS
      run: |
        cd travelbot-ipa-builder
        cap sync ios

    - name: Build iOS project with Xcode
      run: |
        cd travelbot-ipa-builder/ios/App
        # Build the app without signing
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          archive

    - name: Create unsigned IPA
      run: |
        cd travelbot-ipa-builder/ios/App
        # Create export options
        cat > export-options.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
        </dict>
        </plist>
        EOF
        
        # Export IPA
        xcodebuild -exportArchive \
          -archivePath App.xcarchive \
          -exportPath ./build \
          -exportOptionsPlist export-options.plist \
          -allowProvisioningUpdates
        
        # Create export options for development
        cat > exportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key>
          <string>development</string>
          <key>compileBitcode</key>
          <false/>
          <key>stripSwiftSymbols</key>
          <true/>
          <key>thinning</key>
          <string>&lt;none&gt;</string>
        </dict>
        </plist>
        EOF
        
        # Build and archive
        xcodebuild clean archive \
          -project TravelBot.xcodeproj \
          -scheme TravelBot \
          -configuration Release \
          -archivePath build/TravelBot.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        
        # Export IPA
        xcodebuild -exportArchive \
          -archivePath build/TravelBot.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath build/
          
        # Rename IPA file
        mv build/TravelBot.ipa build/TravelBot-4.0.0.ipa 2>/dev/null || true
        
        # List build results
        ls -la build/

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: travelbot-ios-app
        path: |
          travelbot-ipa-builder/ios/App/build/*.ipa
        retention-days: 30

    - name: List build results  
      run: |
        echo "=== Build Results ==="
        ls -la travelbot-ipa-builder/ios/App/build/ || echo "Build directory not found"
        find travelbot-ipa-builder/ios/App -name "*.ipa" -type f || echo "No IPA files found"
