name: Build TravelBot iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'travelbot-ipa-builder/package-lock.json'

    - name: Install Capacitor CLI
      run: |
        npm install -g @capacitor/cli @ionic/cli
        cap --version

    - name: Navigate to Capacitor project and install dependencies
      run: |
        cd travelbot-ipa-builder
        npm install

    - name: Sync Capacitor iOS
      run: |
        cd travelbot-ipa-builder
        cap sync ios

    - name: Build iOS project with Xcode
      run: |
        cd travelbot-ipa-builder/ios/App

        # Verify workspace exists
        if [ ! -d "App.xcworkspace" ]; then
          echo "❌ Error: App.xcworkspace not found. Capacitor sync may have failed."
          exit 1
        fi

        # Build and archive the app without signing
        echo "🏗️ Building and archiving iOS app..."
        xcodebuild clean archive \
          -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -allowProvisioningUpdates

    - name: Create unsigned IPA
      run: |
        cd travelbot-ipa-builder/ios/App

        # Verify archive exists
        if [ ! -d "App.xcarchive" ]; then
          echo "❌ Error: App.xcarchive not found. Previous build step may have failed."
          exit 1
        fi

        # Create build directory
        mkdir -p ./build

        echo "📦 Creating IPA manually from .app bundle..."
        
        # Find the .app bundle in the archive
        APP_PATH=$(find App.xcarchive -name "*.app" -type d | head -1)
        
        if [ -z "$APP_PATH" ]; then
          echo "❌ Error: No .app bundle found in archive"
          echo "Archive structure:"
          find App.xcarchive -type d | head -10
          exit 1
        fi
        
        echo "✅ Found app bundle: $APP_PATH"
        
        # Create Payload directory and copy app
        mkdir -p ./build/Payload
        cp -R "$APP_PATH" ./build/Payload/
        
        # Create IPA by zipping Payload directory  
        cd ./build
        zip -r TravelBot-4.0.0.ipa Payload/
        cd ..
        
        echo "✅ IPA manually created: TravelBot-4.0.0.ipa"
        
        # List final build results
        echo "=== Final Build Results ==="
        ls -la ./build/

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: travelbot-ios-app
        path: |
          travelbot-ipa-builder/ios/App/build/*.ipa
        retention-days: 30

    - name: List build results
      run: |
        echo "=== Build Results ==="
        ls -la travelbot-ipa-builder/ios/App/build/ || echo "Build directory not found"
        find travelbot-ipa-builder/ios/App -name "*.ipa" -type f || echo "No IPA files found"
