name: Update Docs + Changelog

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  append-log-and-deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Append commit to docs/updates.json
        run: |
          FILE="docs/updates.json"
          SHORT_SHA=$(git rev-parse --short HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%s)
          DATE=$(date -u +%Y-%m-%d)

          if [ ! -f "$FILE" ]; then echo "[]" > "$FILE"; fi

          node - "$DATE" "$SHORT_SHA" "$COMMIT_MSG" <<'EOF'
          const [date, sha, msg] = process.argv.slice(2);
          const fs = require('fs');
          const file = 'docs/updates.json';
          const data = JSON.parse(fs.readFileSync(file, 'utf8'));
          data.push({ date, version: sha, description: msg });
          fs.writeFileSync(file, JSON.stringify(data, null, 2));
EOF

      - name: Commit and push changelog
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add docs/updates.json
          git commit -m "📜 Update changelog with $SHORT_SHA [skip ci]" || echo "No changes"
          git push

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
