name: Update Docs + Changelog

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  append-log-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract commit message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

      - name: Check commit message
        run: |
          if [[ "$COMMIT_MESSAGE" == *"[skip ci]"* ]]; then
            exit 0
          fi

      - name: Append commit to docs/updates.json
        run: |
          FILE="docs/updates.json"
          SHORT_SHA=$(git rev-parse --short HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%s)
          DATE=$(date -u +%Y-%m-%d)

          if [ ! -f "$FILE" ]; then echo "[]" > "$FILE"; fi

          node scripts/update_log.js "$DATE" "$SHORT_SHA" "$COMMIT_MSG"

      - name: Commit and push changelog
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add docs/updates.json
          git commit -m "📜 Update changelog with $SHORT_SHA [skip ci]" || echo "No changes"
          git push

      - name: Debug artifact contents
        run: |
          echo "Contents of docs directory:"
          ls -R docs
